obstacle_range: 3
footprint: [[0.2, 0.25], [0.2, -0.25], [-0.2, -0.25], [-0.2, 0.25]]
observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: lidar_frame
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
  inf_is_valid: true
  raytrace_range: 100.0
